"""
Django settings for voting project (Render-ready).

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path

# ------------------------------
# Base directory
# ------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------
# Security
# ------------------------------
# Use environment variable for SECRET_KEY in production
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key')  

# Use environment variable for DEBUG in production
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ------------------------------
# Allowed hosts (Render fix)
# ------------------------------
ALLOWED_HOSTS = [
    'voting-system-s9kz.onrender.com',  # Your actual Render app URL
    '.onrender.com',                     # optional wildcard for subdomains
]

# ------------------------------
# Application definition
# ------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'vote.apps.VoteConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'voting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'voting.wsgi.application'

# ------------------------------
# Database
# ------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ------------------------------
# Password validation
# ------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------
# Internationalization
# ------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# ------------------------------
# Static files (CSS, JS, Images)
# ------------------------------
STATIC_URL = '/static/'  
STATIC_ROOT = BASE_DIR / 'staticfiles'   # For collectstatic in production
# Include app static directories for development
STATICFILES_DIRS = [
    BASE_DIR / 'vote' / 'static',
]

# ------------------------------
# Media files (uploads)
# ------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ------------------------------
# CSRF Trusted Origins (for Render HTTPS)
# ------------------------------
CSRF_TRUSTED_ORIGINS = [
    'https://voting-system-s9kz.onrender.com',
]

# ------------------------------
# Authentication backends
# ------------------------------
AUTHENTICATION_BACKENDS = [
    'vote.backends.AdmissionNumberBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ------------------------------
# Default primary key field type
# ------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'