# Generated by Django 6.0.3 on 2026-03-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudent',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
