# Generated by Django 5.2.5 on 2026-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_vote_unique_together_vote_unique_user_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudent',
            name='is_ussd_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolstudent',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
