# Generated by Django 5.2.5 on 2026-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_schoolstudent_is_ussd_registered_schoolstudent_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstudent',
            name='pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
