# Generated by Django 6.0.3 on 2026-03-25 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_votingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
