# Generated by Django 5.2.5 on 2026-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_votingsession_results_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public comment'), ('admin', 'Admin only')], default='public', max_length=20),
        ),
    ]
